### ISSUE TITLE
add context to git commit message

### ISSUE THREAD

**Issue by warengonzaga** [warengonzaga/magic-commit#1]
Suggested by @jofftiquez; thanks for the support, bro!

`<emoji> category (context): title`

To start, find the `config.json` file and modify the prompt to follow this suggested format. This task requires AI prompt skills. If you have any questions or thoughts about this, let me know.

**Comment by Abhinav-Bansal751** [comment]
@warengonzaga hope its ok now,i dont know  much about conflicts but i have tried.please see it again.

**Comment by warengonzaga** [comment]
Closing this now, as it is already pushed to `dev` branch.
