### ISSUE TITLE
keep the logo at the top of the CLI

### ISSUE THREAD

**Issue by warengonzaga** [warengonzaga/magic-commit#17]
When we added version #13, the logo disappeared when giving suggestions. We want to keep the logo when executing a command or making changes in the terminal UI. Let's keep the logo/branding intact.

Goal:
- Make the logo/branding sticky at the top of the terminal UI.
- Ensure that you follow the updates in #16

**Comment by Snehalgupta-07** [comment]
Hi i can do this task can u pls assign it to me :)

**Comment by spc-28** [comment]
@warengonzaga Can i work on this?

**Comment by warengonzaga** [comment]
Feel free @spc-28 just submit a PR.

**Comment by warengonzaga** [comment]
Kindly fix the issue with missing logo upon showing you a suggestion for commit message. @spc-28

**Comment by warengonzaga** [comment]
Closing this one! Thank you for your contribution @spc-28
