### ISSUE TITLE
Can't use magicc command

### ISSUE THREAD

**Issue by Zcedd** [warengonzaga/magic-commit#3]
![image](https://github.com/warengonzaga/magic-commit/assets/58856158/cad645d1-8189-41ef-a061-aa627fc7bfd5)

**Comment by warengonzaga** [comment]
Hey @Zcedd can you try with git bash instead?

**Comment by Zcedd** [comment]
Still show the same error.

**Comment by warengonzaga** [comment]
It looks like the node is in your current profile. @Zcedd 
Can you try the DevHome and, from there, use the Node.js package?

Also, I'm not able to replicate your issue, as on my end; it is working as usual.
![image](https://github.com/warengonzaga/magic-commit/assets/15052701/2ad6a25f-322b-4b31-8b59-c7da16e81638)

**Comment by warengonzaga** [comment]
Otherwise, don't install it on your machine and just use "npx magicc" @Zcedd

**Comment by warengonzaga** [comment]
Closing this as I'm unable to replicate the issue.
