### ISSUE TITLE
add better selection when asking for commit suggestion

### ISSUE THREAD

**Issue by warengonzaga** [warengonzaga/magic-commit#9]
Instead of typing the answer after the commit suggestion, selecting using the arrow keys is much better.

We can use something like this: https://github.com/vadimdemedes/ink-select-input.
If you can take it, let me know! The project uses https://github.com/vadimdemedes/ink

**Comment by spc-28** [comment]
Can i work on this?

**Comment by warengonzaga** [comment]
Hey @spc-28 feel free!

**Comment by warengonzaga** [comment]
Don't forget to read the [contributing](https://github.com/warengonzaga/magic-commit/blob/main/contributing.md) file!

**Comment by spc-28** [comment]
ok

**Comment by warengonzaga** [comment]
Thank you for your contribution @spc-28. We can close this now as the changes have been added to the `dev` branch and are currently pending be merged to the `main` branch via pending PR #13
